### ISSUE TITLE
Issue: mps-youtube is unable to play videos with non-standard ASCII symbols in the title

### ISSUE THREAD

**Issue by rosen1000** [mps-youtube/mps-youtube#1067]
## Issue
When trying to play music with non English characters in the title, mps-youtube it gives a lot of errors
Error log: https://pastebin.com/nZhN9Hct
Example crashing characters: 『』いてみた

## My Environment
```
mpsyt --version
mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.2 (youtube-dl backend)
youtube-dl version : 2019.09.28
Python version     : 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.3.0-7629-generic-x86_64-with-Ubuntu-19.10-eoan
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/rosen1000/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8
env:LANGUAGE       : en_US:en
```
```
mpv --version
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.14.100 (runtime 56.22.100)
   libavcodec      58.18.100 (runtime 58.35.100)
   libavformat     58.12.100 (runtime 58.20.100)
   libswscale      5.1.100 (runtime 5.3.100)
   libavfilter     7.16.100 (runtime 7.40.101)
   libswresample   3.1.100 (runtime 3.3.100)
ffmpeg version: 4.1.4-1build2pop1~1573838760~19.10~c4dd25c
```

**Comment by deracinator** [comment]
> "Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update" ... quoted from your own error log dump.
try updating your youtube-dl version and try again

**Comment by rosen1000** [comment]
I am not that stupid i have seen that error but im already running latest youtube-dl
`
youtube-dl --version
2020.03.24
`

**Comment by deracinator** [comment]
Then can you provide more meaningful error logs please ?! Because I can't reproduce this behavior, all videos with the characters you pointed out and even the ones with the whole title in chinese or japanese characters are playing just fine.
The error log you sent just shows that the youtube-dl version that your mpsyt installation is using is **totally** out-of-date.
Your mpsyt is using `youtube-dl version : 2019.09.28`, and this seems to be the only issue that's causing your crashings AFAICS.
If you have youtube-dl already updated to the latest release and `mpsyt --version` is still showing it as `2019.09.28` what you probably have is a conflict, eg. you installed by mistake one version using `pip` and other one with your distro package manager, or something like that.
Try and make sure that no conflicts exist and your system has only one `youtube-dl` installation. This is the most likely reason that mpsyt is not using the right version

**Comment by rosen1000** [comment]
Apparently i am dumb, mpsyt used apt version of youtube-dl (2019.09.28) so it was easily fixed buy removing apt ydl and running:

`pip3 install youtube-dl`

Thanks for the help!
