### ISSUE TITLE
Resetting Volume After Every Video

### ISSUE THREAD

**Issue by DevMoore94** [mps-youtube/mps-youtube#145]
It is rather tedious to have to reset the volume to the level you want it at after every video. Would it be possible to have the option to set a variable to true so that the volume for every video plays at the same spot?

**Comment by tarwich** [comment]
Having this problem for audio on OSX.
> Mac OS X 10.10.2.14C109
> arch: x86_64
> MPlayer: 1.1-4.2.1
> mpsyt: development HEAD

**Comment by tarwich** [comment]
I'm so sorry guys. I try really hard to fix things before posting. This solution (**softvol**) fixed my problem.
[get mplayer to start with a default volume other than 25%](http://superuser.com/a/24856)

**Comment by np1** [comment]
Cool, thanks for the info.

@DevMoore94 Is this still an issue for you with mplayer? If so could you try entering (within mps-youtube):

`set playerargs -softvol`

**Comment by tarwich** [comment]
This site says that the new version of mplayer supports a `-volume 0-100` argument. I tried it and it works great in playerargs. No more softvol for me!
http://ubuntuforums.org/archive/index.php/t-1212414.html

If you want to close this issue, I can test it with video playlists and see if it works. Of course, I can see how people would think that this is an mpsyt thing, since so much of mpsyt "just works" right out of the box. If mpsyt were more broken, then people would assume it's not your fault.

**Comment by Svinto** [comment]
I have the same problem. Volume resets to 50% after every track. But:
- I'm using set show_video false, only playing the audio in the terminal.
- I'm using mpv. mplayer is not installed.

I'm running Arch Linux on a x64 system.

**Comment by gillron** [comment]
This is very annoying, I love mps and I think it's flawless on what it does, but this is very annoying, especially when you're on WinXP (No Per-Program Volume Settings).

Any planned patch addressing this?

**Comment by ids1024** [comment]
I'm not sure if this is really an issue with mps-youtube so much as with mpv/mplayer.

@gillron If you're using mplayer, try mpv instead.

**Comment by gillron** [comment]
@ids1024 , thank you for your time

I'm already using mpv. 

>I'm not sure if this is really an issue with mps-youtube so much as with mpv/mplayer.

Not quite sure if mpv is supposed to store volume changes upon termination. I wasn't able to find any open tickets regarding this problem on the mpv player git repo.

**Comment by ids1024** [comment]
@gillron As mentioned above, you can use something like `set playerargs --volume 20` to set the volume to some specific value.

Really, using Windows XP is a bad idea for various reasons (it is also rather insecure). If you are using XP and are not just mentioning it, also note that, if I recall correctly, mpv dropped support for XP in recent versions.

**Comment by gillron** [comment]
>Really, using Windows XP is a bad idea for various reasons 

Debatable

>(it is also rather insecure). 

Very well aware of that , unfortunately

>if I recall correctly, mpv dropped support for XP in recent versions.

Correct

Well, I have nothing else to say except thanking you for your time :). I'll see if I can come up with a workaround.

Best Regards

**Comment by lol768** [comment]
Somewhat off-topic but:

>Debatable

It's not. XP is [EOL](https://www.microsoft.com/en-gb/WindowsForBusiness/end-of-xp-support). The only way it would be acceptable would be if the machine was airgapped from any other machines or devices ... and since you're trying to use a tool which streams from YouTube, it would appear that this is not the case.

Unless of course you have a CSA with Microsoft. But I hear those are pricey.

Best of luck finding a workaround, though :)
