### ISSUE TITLE
artist, album, song title metadata

### ISSUE THREAD

**Issue by ccorcos** [mps-youtube/mps-youtube#209]
When I download a song, it would be sweet if the metadata would already be filled out... Is that something thats not too difficult?

**Comment by ccorcos** [comment]
this an awesome program by the way. great job with the interface

**Comment by EduardoRT** [comment]
This would be nice, if you want to open your music in iTunes on somewhere else and have it display correctly.

**Comment by np1** [comment]
I have implemented this on develop branch although it's quite basic.
It tries to determine the artist and title from the YouTube video title by splitting it on " - "
Otherwise the entire title is set as the metadata title for the audio file.
It should be better than not tagging any data.

**Comment by ids1024** [comment]
> It tries to determine the artist and title from the YouTube video title by splitting it on " - "

Unfortunately, this is not always reliable.  Some videos have this in the reverse order.

Is it possible to get this data for some videos?  I looked up a random song ([this one](http://www.youtube.com/watch?v=auLBLk4ibAk)), and it includes an album name in what looks like metadata rather than just a description.  You can also get more reliable data specifically when using the `album` command like you suggested earlier for implementing something else.

**Comment by np1** [comment]
I realise it's far from perfect, that's why I labeled it rudimentary and basic. I figured it's a good place to start and since we are calling ffmpeg/avconv to do the remuxing it would be a good opportunity to add in some metadata.

I have seen that some videos have it as "title - artist" although a quick search for popular songs and artists indicates that in the large majority of cases when there is a single ` - ` that the artist precedes the title as opposed to vice-versa.

The `extract_metadata` function could be expanded (perhaps by querying an online resource) to make sense of the reversed case you point out or to make more sense of a YouTube title such as 

`Robin Thicke ft. TI, Pharrell - Blurred Lines [LYRICS] + [FREE MP3 DOWNLOAD] (no survey)`

by returning clean data for artist and title.

We could also implement checks such as only attempting to resolve music type metadata when the video is in YouTube's music category.

I thought my baseline implementation would be more useful than adding nothing, although I can appreciate that potentially incorrect tags may be considered worse than no tags.

Making use of the MusicBrainz data from the `album` command would help with that case, it might be best to wait until we have split the code into separate files.

I'm not sure where you are seeing the album name in the link you gave, I see:
```
Published on Dec 21, 2012

Amazon: http://bit.ly/Rush2112SDE_Web



Music video by Rush performing Tom Sawyer. (C) 1981 The Island Def Jam Music Group and Anthem Entertainment

    Music
        "Tom Sawyer" by Rush ( • • )
    Artist
        Rush
    Category
        Music
    License
        Standard YouTube License

```

**Comment by ids1024** [comment]
Ok, it looks like that video doesn't have the album.  However, it does look like a better way to get the title and artists, where available.  But anyway, this implementation is better than nothing and should be correct most of the time.

**Comment by tepf** [comment]
Is there a chance that this feature might get picked up again? @np1 suggested querying a music database to make sure which is probably the best way.

A simpler one would be to compare with the other songs in the download queue. If all songs seem to have "Band" as the artist name and the current downloading has "Band" in the title then it might be reversed.

**Comment by ids1024** [comment]
@tepf Feel free to implement such a thing and submit a pull request.

**Comment by vn-ki** [comment]
I would like to work on this feature. I have already implemented this in my own project, YouTube Player. You can get proper album art and other metadata using last.fm. It works for a lot songs on YouTube. This feature could be extended to show metadata while using mpris controllers.

![screenshot2](https://user-images.githubusercontent.com/31964688/33808064-2471b762-de06-11e7-83fd-8566af34465e.png)
