### ISSUE TITLE
Clear screen another way 

### ISSUE THREAD

**Issue by vbmvbm** [mps-youtube/mps-youtube#239]
I think there's a better way to clear the terminal than printing two hundred line breaks.
Inside the methods `screen_update` and `search_album`, in my machine I've replaced `xprint(g.blank_text)` with `os.system('cls' if mswin else 'reset')`, and at least for me I think it's much better, since I can easily reach the beginning of a large playlist. 
It could be added as an option if you think it may lead to compatibility issues.

**Comment by bendem** [comment]
`print("\033[2J\033[;H")` is the ansi way to clear the console and it should be supported by linux, mac and windows.

Else than that, I would use `clear` instead of `reset` for other targets than windows. `reset` can be a bit slow some time.

**Comment by vbmvbm** [comment]
Printing that string in Python or using the `clear` command will both add some lines to the terminal and scroll it down till the end, unlike `reset` on Linux and `cls` on Windows. Thus, it is hard to find the start of a very large playlist.

However, as you pointed, `reset` is a bit slow indeed. According to [this answer](http://superuser.com/a/123185), `tput reset` is a good choice for this: it really clears the terminal, and it's fast. I've checked it now by editing those lines again. 

Since there's more than a way to do it, mpsyt could let the user choose it, just like it does with the player. In case the user does not set it or leaves it blank, the current behaviour (print 200 '\n') could be used.

**Comment by ids1024** [comment]
I think this may be a good idea, but I'm not sure which method is best. Google searching suggests that Windows does not (at least by default) support ansi escape codes, so that method cannot be used, at least not on all  systems.

Perhaps a good method would be something like this:

    if mswin:
        subprocess.call(['cls'])
    elif has_exefile('tput'):
        subprocess.call(['tput', 'reset'])
    else:
        xprint(g.blank_text)

Does that seem like a good solution?

**Comment by ids1024** [comment]
It seems that this results in the text being aligned to the bottom of the screen rather than the top. Probably not a good thing...

**Comment by bendem** [comment]
Isn't that the normal/current behavior?
![](http://i.imgur.com/eSsezqs.png)

**Comment by ids1024** [comment]
Sorry, meant to say the reverse. It is currently bottom-aligned, but this makes it top-aligned.

**Comment by vbmvbm** [comment]
> Does that seem like a good solution?

Yes, it would be a very good solution.

Regarding the vertical alignment, IMHO it makes no practical difference. Anyway, if bottom alignment is really required, it should be quite easy to print something like `max(H - h, 0)` newlines before showing the search results or playlist items, where `H` is the terminal height and `h` is the number of lines which will be printed (from "Num  Title" to "> " in @bendem's screenshot).

**Comment by ids1024** [comment]
Ok, implemented. I'm not sure I agree that it doesn't matter, but the solution of adding a few newlines as well could work.

The issue I have with it is that the line where the command is entered is now at varying positions rather than consistently the bottom. I think that could possibly be annoying, but I'll have to use it more to see.

**Comment by bendem** [comment]
I think aligning stuff at the top isn't a bad change, but as you pointed out, having the input position change is the worst. Would it make sense to print blank lines between the "main informations" and the "status/input" lines?

**Comment by ids1024** [comment]
@bendem Good idea; implemented in ca56aec7ed3d56066d42c57613784a4fe98ae8ab.

I think using this method instead of just printing a bunch of newlines is good, but if it leads to issues I will revert the changes.

**Comment by bendem** [comment]
Awesome :+1:

**Comment by viniciusbm** [comment]
Nice improvement!

**Comment by vbmvbm** [comment]
Nice improvement!

**Comment by ids1024** [comment]
It seems there is an issue with this; it is currently misaligned for the `album` command. This should probably be easy enough to fix.

Unrelated to that, I am not quite sure if this is an improvement. It could even be advantageous to just not clear the screen at all, as makes sense with a command prompt based interface, and it may be good to add a setting for that.

The number of newlines could be based on the screen size instead of being just an arbitrary large number. That would probably be a bit better.

Anyway, a curses interface (#139) would bring this functionality.

**Comment by ids1024** [comment]
The changes have been reverted (for now) for the reasons stated above and due to other cases where the top line ended up cut off.
