### ISSUE TITLE
Error fetching playlist PL0sHkSjKd2roowJbtmJJdBoCLq4eE6KMP

### ISSUE THREAD

**Issue by Jimmm** [mps-youtube/mps-youtube#347]
This error comes with all 
#PopularOnYouTubeGermany
https://www.youtube.com/playlist?list=PL0sHkSjKd2roowJbtmJJdBoCLq4eE6KMP
#PopularOnYouTube(AnyCountry)

My steps
1. //PL0sHkSjKd2roowJbtmJJdBoCLq4eE6KMP
2. 1
3. Error

**Comment by ids1024** [comment]
Strange. It seems the issue is the name of this video: https://www.youtube.com/watch?v=puxSGf7dQDA&list=PL0sHkSjKd2roowJbtmJJdBoCLq4eE6KMP&index=53

The title is formatted in the json as `"RELAX ROUTINE \U0001f64f MEINE TIPPS GEGEN STRESS | KINDOFROSY"`, but the `\U` escape code is invalid. `\u` would be valid, but it should have four characters after it, not eight. This is just strange...

**Comment by ids1024** [comment]
I believe this should be fixed in version 0.2.6.
