### ISSUE TITLE
[Feature Request] Open in default web browser

### ISSUE THREAD

**Issue by maricn** [mps-youtube/mps-youtube#355]
Hi guys,

Do you think it would be useful to have a command (or button during playback) which would open YouTube URL in default (or configurable) web browser?
I often want to save a video to my account playlist or to subscribe to a channel, or whatever, but I must repeat a few steps until I get there. I figure this isn't so hard to implement...

**Comment by Wildefyr** [comment]
This would be a nice stop gap solution to the fact we cannot log into our google youtube accounts with mpsyt.

**Comment by BensonQiu** [comment]
Hi,

[I'm](https://github.com/BensonQiu) working on a group project with [Femi](https://github.com/aquafemi), [Paul](https://github.com/paulnicolet), [Rohan](https://github.com/rjvani), and [Tommy](https://github.com/tommyhtc), and we're interested in contributing to mps-youtube. We don't have much experience with open source contributions, but we would like to work on [#90](https://github.com/mps-youtube/mps-youtube/issues/90), [#375](https://github.com/mps-youtube/mps-youtube/issues/375), and [#355](https://github.com/mps-youtube/mps-youtube/issues/355) as a group over the next 2-3 weeks. Would these contributions be helpful for the project?

We have read the [contributing](https://github.com/mps-youtube/mps-youtube/blob/develop/CONTRIBUTING) document, but we wanted to post here to express interest. We also wanted to see if anyone was already working on these issues. Since we would like to work on three open issues, I'm posting this message three times (sorry for the spam!).

Regards,
Benson, Femi, Paul, Rohan, and Tommy

**Comment by Wildefyr** [comment]
Just thought I'd mention in addition to anyone wanting this at the moment, it's possible to get url recognition inside the terminal itself, i.e. urxvt-perls provides extensions for this functionality for rxvt-unicode. You can then see the youtube url with the `url #` command in mpsyt.
