### ISSUE TITLE
Does userpl work with google account?

### ISSUE THREAD

**Issue by ldmdev** [mps-youtube/mps-youtube#368]
Hello,
I'm trying to retrieve my public playlist using "userpl" command but I get "No playlists found for: user: myusername". My youtube account is the google one, the playlist is public and I can find it via pl command.

Thank you!

**Comment by Wildefyr** [comment]
Go to your youtube channel page (click on 'My Channel' on the left handside nav bar), the name it shows in the url is the actual name of your user/channel. If you then do userpl $name it should come up with your public playlists.

**Comment by ldmdev** [comment]
Hi Wildefyr,
thank you for your answer. 
I tried as you said: when I go to my channel the address is https://www.youtube.com/channel/UC-cW5lWCpVUI3CmQsscDXuw
so if I try 
`userpl UC-cW5lWCpVUI3CmQsscDXuw`
the result is 
`User UC-cW5lWCpVUI3CmQsscDXuw not found.`

:worried:

**Comment by Wildefyr** [comment]
Yes, that is your google account name. (They're all integrated nowadays). It seems you haven't set a custom channel name for the url of your channel page. Now it has been sometime since I created my google account and they have appeared to have changed the way you can set your custom channel name. [This](https://support.google.com/youtube/answer/2657968?ref_topic=3024172&hl=en) is the only useful thing I have been able to find from google's documentation. It appears you have to now meet some eligibility rules to 'brand' your page and if you don't qualify you can't. However, this is the only way I know of getting that custom channel url. Perhaps mps-youtube could detect google account playlists instead of only relying on custom channel urls?

**Comment by ids1024** [comment]
It is odd. The command `user Lucio Di Matteo` lists your videos, but `userpl` doesn't work...

**Comment by joelostblom** [comment]
I am also not able to find my userplaylists using `userpl` or `user`. I tried my login name, the youtube user id, and the youtube channel id (the user id prefixed with 'UC'). I did not create my account via google and I am able to find the playlists individually via the `pl` command.

**Comment by ids1024** [comment]
Hm, @ldmdev's playlist does not seem to show up in a search for its title (`//test_pl_0001`, or on the Youtube website). @joelostblom Is it the same for you? If so, youtube is excluding it from search results for some reason, and I don't know if there is anything that can be done to prevent that.

**Comment by joelostblom** [comment]
Yes, for all playlists but one, I have to type in the url, I can't search for the title using `pl`. However, there is one single playlist which shows up when I search for its title, this is the oldest playlist I have, created back in June 2014. My playlists created in November 2014 and onwards does not show up when using `pl`.
