### ISSUE TITLE
Avoid duplicated videos in a playlist

### ISSUE THREAD

**Issue by alfonsomga** [mps-youtube/mps-youtube#374]
It would be nice to mpsyoutube support this because at least for me it is a bit annoying to have the same video repeated in a long playlist.

Maybe can we check when adding a new video to a playlist verify if the **VIDEO ID** is unique in that playlist? then if it already exists discard it?

**Comment by BensonQiu** [comment]
Hi,

[I'm](https://github.com/BensonQiu) working on a group project with [Femi](https://github.com/aquafemi), [Paul](https://github.com/paulnicolet), [Rohan](https://github.com/rjvani), and [Tommy](https://github.com/tommyhtc), and we're interested in contributing to mps-youtube. We don't have much experience with open source contributions, but we would like to work on [#90](https://github.com/mps-youtube/mps-youtube/issues/90), [#374](https://github.com/mps-youtube/mps-youtube/issues/374), and [#355](https://github.com/mps-youtube/mps-youtube/issues/355) as a group over the next 2-3 weeks. Would these contributions be helpful for the project?

We have read the [contributing](https://github.com/mps-youtube/mps-youtube/blob/develop/CONTRIBUTING) document, but we wanted to post here to express interest. We also wanted to see if anyone was already working on these issues. Since we would like to work on three open issues, I'm posting this message three times (sorry for the spam!).

Regards,
Benson, Femi, Paul, Rohan, and Tommy

**Comment by BensonQiu** [comment]
Is there a use case where someone might want to have duplicate videos in a single playlist?

**Comment by ids1024** [comment]
@BensonQiu Good question, and one I thought of when I saw this issue. I cannot really think of a reason, but that does not mean someone is not using it in that way.

Perhaps to solve that, it could print a warning instead of rejecting the video.

**Comment by ids1024** [comment]
Warning of duplicates added in #383.

**Comment by alfonsomga** [comment]
@ids1024  :+1:
