### ISSUE TITLE
youtube id needed for download command

### ISSUE THREAD

**Issue by marto1** [mps-youtube/mps-youtube#375]
Hi,
I'm using a custom download command, but I'm missing youtube id substitute. I digged through the source and it's in the `download` function - song.ytid, but it's not passed to the _download function. So is there a way to fetch the id without modifying code?

**Comment by marto1** [comment]
Ah, I meant it's not passed to `external_download`

**Comment by ids1024** [comment]
Implemented in commit e05f9977bc212e91de7ee43e8129a2594aae4265.

Out of curiosity, what do you want this for?

**Comment by marto1** [comment]
Great! For a experimental youtube-mp3.org download client(not yet released)

**Comment by BensonQiu** [comment]
Hi,

[I'm](https://github.com/BensonQiu) working on a group project with [Femi](https://github.com/aquafemi), [Paul](https://github.com/paulnicolet), [Rohan](https://github.com/rjvani), and [Tommy](https://github.com/tommyhtc), and we're interested in contributing to mps-youtube. We don't have much experience with open source contributions, but we would like to work on [#90](https://github.com/mps-youtube/mps-youtube/issues/90), [#375](https://github.com/mps-youtube/mps-youtube/issues/375), and [#355](https://github.com/mps-youtube/mps-youtube/issues/355) as a group over the next 2-3 weeks. Would these contributions be helpful for the project?

We have read the [contributing](https://github.com/mps-youtube/mps-youtube/blob/develop/CONTRIBUTING) document, but we wanted to post here to express interest. We also wanted to see if anyone was already working on these issues. Since we would like to work on three open issues, I'm posting this message three times (sorry for the spam!).

Regards,
Benson, Femi, Paul, Rohan, and Tommy
