### ISSUE TITLE
overriding settings from the command line should only affect the current invocation

### ISSUE THREAD

**Issue by Vrihub** [mps-youtube/mps-youtube#455]
The `mpsyt set... , set...` feature is very helpful, but it seems to change mpsyt settings permanently, and this can lead to unexpected results in subsequent invocations of the program.

Scenario: as I do for many UNIX programs, I wrote a shell script wrapper for mpsyt, for a very specific need which requires overriding the standard settings via command line parameters. Currently, if I run mpsyt directly, after running my wrapper, mpsyt will keep using the special settings, instead of the expected standard settings.

The expected behaviour, like for standard UNIX programs, is that overriding settings by command-line options only affects the current instance of the program, without permanently changing settings in the program configuration file.

**Comment by BlackCapCoder** [comment]
I created a pull request fixing this: https://github.com/mps-youtube/mps-youtube/pull/797

**Comment by BlackCapCoder** [comment]
@Vrihub What is the expected behavior if the user manually changes a setting after having launched mpsyt with temporary changes to the settings?

I could:
* Save all changes, including the ones set automaticaly
* Save only the manual changes
* Not save any changes

Another option to add something like a `--nosavesettings` flag.

**Comment by Razesdark** [comment]
If I can add a few cents to the discussion.
I think that saving only manual changes is the way to move foward. I think one of the expected ways that `set` is supposed to work is that you can set new values and that the software remembers it. I wouldn't want that to change or be ambiguous in any way. So if a user sets a value, it should persist.

Personally I would be more fond of a solution where instead of calling `set` from the commandline, we use normal `--something` looking arguments. For example `--set key=value`. And maintain a separate list of configurations set in this manor. That way we could actually alter the list of configurations outputted to the screen in a way where it reflects which configurations are overwritten by the new arguments. I think it is important that we visually convey that there are temporate settings applied, to the user.

I also think that when a user sets a configuration that is currently being overwritten by a temporary one, we remove the temporary one making the users last value the one that counts.

**Comment by Vrihub** [comment]
> @Vrihub What is the expected behavior...

Thank you for working on this issue!

My only concern here was the behaviour of options set on the command line when invoking mpsyt; my model is the way UNIX programs usually work: command line options override configuration file options, but only for the current instance. I think this is a bug that should be fixed.

Re what happens for options that are set interactively from within the program: this is more a design decision than a bug: mpsyt always save settings, many programs never save any settings automatically and have some "Save settings" command to explicitely save the whole current configuration. I would prefer this, but it would be such a radical change, so I won't advocate it here, I'd just retain the current behaviour, to keep changes to a minimum (i.e. I would go your "Save only the manual changes" option).

Perhaps the best solution is the one used by `midnight commander`: it has a `Auto save setup` setting, so the user can choose one model or the other. If we could add something like this to mpsyt (with default setting to `True`, to keep the backwards compatibility), that would be very cool! If you agree, maybe I can try to help implementing it...

**Comment by BlackCapCoder** [comment]
I second the `auto save setup` setting. It has no chance of breaking backwards compatibility and does not require introducing a notion of temporary or automatic settings. It seems like the cleanest solution.

**Comment by ids1024** [comment]
> I second the auto save setup setting. It has no chance of breaking backwards compatibility and does not require introducing a notion of temporary or automatic settings. It seems like the cleanest solution.

I don't particularly like this solution, though I'm not sure what's best.

> Personally I would be more fond of a solution where instead of calling set from the commandline, we use normal --something looking arguments. For example --set key=value. And maintain a separate list of configurations set in this manor.

I was thinking of the same thing. I'm not sure if this would be better, or if it would be better to have something like `set -t` for temporary settings; the latter could also be used interactively for settings you want to only affect the current session.

**Comment by BlackCapCoder** [comment]
I made a separate (pull request)[#803] implementing `set -t`. The (other one)[#797] implements the `auto save setup` setting.

**Comment by kraetzin** [comment]
#803 has now been merged. Thanks!
