### ISSUE TITLE
Searching and fetching video info takes a while to start

### ISSUE THREAD

**Issue by dlo21** [mps-youtube/mps-youtube#488]
I recently reinstalled mps-youtube through pip, and since I had, It's been significantly slower; It takes about 3 minutes for the program to start, and searching and fetching video info seems to take much, much longer than that.

**Comment by Bleh00** [comment]
I have the same problem on my Ubuntu 16.04 box. It takes about 30 seconds to 2 minutes juste to do a youtube search. At first, I thought that this issue was Youtube related...until I tested mps-youtube on a OpenSuse Tumbleweed VM, where the search was almost instant.
On Ubuntu I have :
mpv version 0.18, mpsyt version 0.2.6, youtube-dl version 2016.06.26, pafy version 0.5.1
And on OpenSuse, I have :
mpv version 0.17, mpsyt version 0.2.6, youtube-dl version 2016.05.16, pafy version 0.5.1

Please, can someone help us ? I realised how much I miss mps-youtube when I can't use it properly :)

**Comment by ids1024** [comment]
@Bleh00 I'm not entirely sure what the problem is. It could be that the OpenSuse install is not using the youtube-dl backend. You can try running `PAFY_BACKEND=internal mpsyt` and see if it is faster, but the internal backend is broken currently when you actually try to play something.

**Comment by Bleh00** [comment]
Holy crap it worked ! :) Thank you sooo much
