### ISSUE TITLE
MPSYT on Android

### ISSUE THREAD

**Issue by ceebu** [mps-youtube/mps-youtube#549]
I am trying to  run MPSYT on Android - I installed Qpython3 from Playstore and using pip console, installed youtube-dl and mps-youtube. But when I run mpsyt, i keep getting error `**"OS Error: [Errno 13] Permission dnied: "data/.config"**` - Not sure if those errors are because of Qpython or MPSYT, but wanted to check if this supposed to work this way

**Comment by ids1024** [comment]
You can try modifying the `get_config_dir()` function in `mps_youtube/paths.py` to return a path the program has access to on android.

Try changing the line `mps_confdir = os.path.join(confdir, "mps-youtube")` to `mps_confdir = "/sdcard/mps-youtube"`.

**Comment by kraetzin** [comment]
I was able to get mpsyt working on Android using [Termux](https://termux.com/). I could only use it to download, however, since there's no usable music player. Not sure if this helps you.

**Comment by ceebu** [comment]
Apologies for the late reply - Thanks kraetzin, I was able to use mpsyt on termux. However, I had trouble running mpv (even though, some people have been able to run mpv on android) - Instead, i installed play-audio and set player to play-audio.

Now, I am able to search and get results, but unable to play the file - i keep getting "error retrying" and after few times it goes back to the result screen.

Is there a way I can help debug what the issue is ? It would be great if mpsyt can use play-audio as the player.

**Comment by ceebu** [comment]
For those looking to run MPSYT on android, I was able to run it using Termux on a Oneplus 2. (Having some difficulties with a S7 though)

Install termux, install mpv , python and using pip install youtube-dl and mps-youtube.  Have been running YouTube successfully since yesterday. Hence closing this issue.

**Comment by afghanPower** [comment]
Where did you find MPV for android?

**Comment by kraetzin** [comment]
If using Termux, just do `apt install mpv`.

**Comment by doriandimov** [comment]
Hi! Aquaris E5s (vegeta lte) Lineage OS 14.1 (Nougat 7.1.1) everything working except video playback. 

Followed @ceebu instructions.
Search_music kept enabled
Disabled fullscreen and 'show_video' (if already disabled changes won't take any effect)
Encoder set to option 1. (MP3 256kbps)
max_res set to 720 (but I guess if you set 1080 nothing wrong would happen, perhaps more data usage on video download)
Audio playback ( -a ) DOES work with keyboard controls (0 vol up, 9 vol down, space pause, enter quit song). Turning screen off does not stop the playback. 
Unable to access external SD card but can change default download location to /storage/emulated/0/whereveryoulike (directory must be created first in order to use it with mpsyt) - give Termux permissions to manage storage.

Mp3 encoder only works for the *.m4a files, the others are downloaded rawly in *.webm 
That's all I got and thanks a lot, @ceebu

**Comment by ceebu** [comment]
@doriandimov  Glad that I could be of help :-)

Ironically, I stopped using mpsyt after few weeks after figuring out how to use it on Android ! I listen when I drive and in that scneario, the user experience was not great and podcasts apps were much more easier to use.
