### ISSUE TITLE
"Sorry this track is not available" in all tracks in Debian Jessie

### ISSUE THREAD

**Issue by MatiasRossi** [mps-youtube/mps-youtube#587]
I have a trouble with mps-youtube. I cant reproduce anything. The player show the legend "Sorry this track is not available" for all tracks. 
I have installed the lastest version of mps-youtube (v0.2.7.1) using pip3
I have installed the lastest version of youtube-dl using pip3. 

I has following the instructions of https://github.com/mps-youtube/mps-youtube/issues/211 and i run: 
`python -c "import pafy; print pafy.new('j8Tcjff_yXQ')"`
The results is here: 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pafy
```
but if i run 
`pip3 install --upgrade pafy`
pip3 show the following message: 
`Requirement already up-to-date: pafy in /usr/local/lib/python3.4/dist-packages`

I already rebooted the machine, and cleared all files in ~/.config/mps-youtube/

Any Ideas? Thanks in advance!

PD: Sorry for my bad english.

**Comment by ids1024** [comment]
The `python -c` line isn't working because `python` is a symlink for python2 on Debian (although I think they're planning on changing that before too long.

You can try the same command with `python3 -c`.

Also post the full output of `mpsyt --version`.

**Comment by MatiasRossi** [comment]
The output of mpsyt --version is
```
mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.3.1 (internal backend)
Python version     : 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/matias/.config/mps-youtube
env:TERM           : xterm
env:SHELL          : /bin/bash
env:LANG           : es_AR.UTF-8
env:LANGUAGE       : es_AR:es

```
The output of python3 -c "import pafy; print pafy.new('j8Tcjff_yXQ')"

  ```
File "<string>", line 1
    import pafy; print pafy.new('j8Tcjff_yXQ')
                          ^
SyntaxError: invalid syntax
```

Thanks in advance!

**Comment by ids1024** [comment]
`(internal backend)`—This means it's not using youtube-dl, although I don't see how that would be the case if you installed both with pip3... unless the environmental variable `PAFY_BACKEND` is set...

Are you sure you installed youtube-dl and mps-youtube correctly using `pip3`?

**Comment by jacwib** [comment]
I have this problem (For some songs only) aswell, mpsyt --version also gives (internal backend), but echo echo "$PAFY_BACKEND" gives no output (aka its not set).

However, a pip3 install youtube-dl fixed it. (Replaced debians (well, in this case ubuntus) version of yt-dl?)

**Comment by MatiasRossi** [comment]
Thanks! 
After the installation of youtube-dl using pip3 (i think i was the debian's repos version) mpsyt is working very fine... 

Strange thing. the playter works correctly until two days ago. But now works again and that's the important part!

Many thanks for the atention and help!

**Comment by jacwib** [comment]
Same here, strangely stopped working. You should probably run a sudo apt remove youtube-dl aswell, to make sure you wont get confused by having two in the future.

**Comment by amartin83** [comment]
Hi,

Since I had the same issue today, I guess it's good to point out, that there seem to be 3 different versions of "youtube-dl":
1) from distro (ubuntu, debian, mint) which is usually old
2) from PIP
3) from main website. Instruction says to put it in: /usr/local/bin/youtube-dl
And sometimes there is a difference in its name like "youtube-dl" vs "youtube_dl".

As I'm using youtube-dl for some other apps, so best way would be, to have just one youtube-dl in the system - for me prefered one is from the main website as it's quickest to be updated and also easiest to update.

Question: is it possible (or will this option be possible in future version of mpsyt) to specify which youtube-dl mpsyt should be using? Mayby to specify a path or it automatically look in default folders of the above 3 points?

P.S.
Thanks for a great app, using it all the time and love how well the application has been thought-out

Kind regards,
AMartin
