### ISSUE TITLE
Repeat song doesn't remember volume

### ISSUE THREAD

**Issue by orschiro** [mps-youtube/mps-youtube#716]
1. Play a song with repeat, e.g. `5 repeat`
2. Lower the volume pressing `9`
3. Wait for the song to repeat

I expect the volume to remain lowered. Instead, volume is reset to 100%.

Tested on Ubuntu 17.10 with mps-youtube version 2.7.1.

**Comment by Razesdark** [comment]
This behaviour is certainly not wanted but sadly there is no easy universal fix.

The way the player works at the moment is that it  Downloads the first file you requested, opens the player which plays the song and shuts down. MPSYT waits for the player to exit before it picks the next song in your playlist and repeats the process and because we don't know the audio level when the player shuts down we can't initiate the next player with the same audio level.

Until we fix this somehow; If you are using `mpv` as your music player of choice, you can use `set playerargs` to specifically set the volume with a `set playerargs --volume=<0-100>` 

Or if you want to just loop one song over and over again `set playerargs --loop=<n or inf>` where `n` is the number of times you want to play the song, or `inf` if you want it to loop forever. Because we only supply the player with one song at the time, this will loop only the first song, even if you select more than one from your search results.

Hope that can be an adequate "hack" for the time being!

**Comment by ritiek** [comment]
#660 does pass relevant `--loop` option if playing a song on repeat with mpv as the player (won't work with other players). It indeed preserves media options just as @Razesdark mentioned.

So, it should work correctly @orschiro's case if using mpsyt from develop branch with player set to mpv.

**Comment by orschiro** [comment]
@ritiek thank you!

> So, it should work correctly @orschiro's case if using mpsyt from develop branch with player set to mpv.

Is there any easy way to install mpsyt from develop branch on Ubuntu 17.10?

**Comment by ritiek** [comment]
@orschiro Try this
```
sudo pip3 install -U git+https://github.com/mps-youtube/mps-youtube.git
```

**Comment by orschiro** [comment]
Do I have to uninstall mps-youtube that I had previously installed using `apt install mps-youtube`?

**Comment by ritiek** [comment]
Yeah, you need to uninstall it before. Sorry, forgot to mention it before.
```
sudo apt purge mps-youtube
```

**Comment by orschiro** [comment]
@ritiek that works great. Thank you so much! Solved my problem. :-)

Please also see https://github.com/mps-youtube/mps-youtube/pull/717
