### ISSUE TITLE
ERROR: Signature Extraction failed: Traceback (most recent call last)

### ISSUE THREAD

**Issue by sz-lhl** [mps-youtube/mps-youtube#718]
I try to search something,it happens on windows

**Comment by ritiek** [comment]
Could you please post the full traceback otherwise it'll be very hard to debug what's causing this error.

**Comment by ceebu** [comment]
I have the same issue - 

Here is the error that I get:

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\youtube.py", line 1070, in _decrypt_signature
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\youtube.py", line 958, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflXHVFyU/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflXHVFyU/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ritiek** [comment]
@ceebu Try again after updating youtube-dl just as it says:

```
$ pip3 install youtube-dl -U
```

**Comment by GenuinePotato** [comment]
Getting the same issue on Ubuntu 16.04 even after updating youtube-dl to the 2017.11.26 version

**Comment by Golars** [comment]
> pip3 install youtube-dl -U

Thanks) It's helps for me.
