### ISSUE TITLE
Mpris2 interfaces don't implement introspection for properties

### ISSUE THREAD

**Issue by FichteFoll** [mps-youtube/mps-youtube#839]
It looks like the mpris2 module doesn't implement any properties. Via https://github.com/FichteFoll/discordrp-mpris/issues/4, I was made aware that the `PlaybackStatus` property isn't implemented and a quick glance at the source seems to indicate that in fact no property is exposed at all. I'm not familiar with the Python `dbus` package, but a quick glance with QDBusViewer seems to confirm this.
(Assuming `dbus` provides the `org.freedesktop.DBus.Introspectable` automatically.)

![2018-06-04_12-54-49](https://user-images.githubusercontent.com/931051/40914123-45911e76-67f7-11e8-8525-2abb154e31ab.png)

**Comment by hrnr** [comment]
The properties are implemented, but they are not introspectable due to limitations of dbus-python we use to implement dbus interface. Even signals for properties should work as expected.

In your screenshot you see that there is `org.freedesktop.DBus.Properties` under `/org/mpris/MediaPlayer2`. That is a standard property interface. Eg.

`GetAll("org.mpris.MediaPlayer2")`
```
{'CanQuit': False,
 'CanRaise': False,
 'CanSetFullscreen': False,
 'DesktopEntry': 'mps-youtube',
 'Fullscreen': False,
 'HasTrackList': False,
 'Identity': 'mps-youtube',
 'SupportedMimeTypes': [],
 'SupportedUriSchemes': []}
```

`GetAll("org.mpris.MediaPlayer2.Player")`
```
{'CanControl': True,
 'CanGoNext': True,
 'CanGoPrevious': True,
 'CanPause': True,
 'CanPlay': True,
 'CanSeek': True,
 'MaximumRate': 1.0,
 'Metadata': {'mpris:artUrl': 'https://i.ytimg.com/vi/S3fTw_D3l10/default.jpg',
              'mpris:length': 307000000,
              'mpris:trackid': '/CurrentPlaylist/ytid/S3fTwD3l10',
              'xesam:album': '',
              'xesam:artist': [''],
              'xesam:title': 'Alt-J (∆) - Taro'},
 'MinimumRate': 1.0,
 'PlaybackStatus': 'Playing',
 'Position': 2987500,
 'Rate': 1.0,
 'Volume': 1.0}
```

For implementation see https://github.com/mps-youtube/mps-youtube/blob/0100a38d3874c53e705d9acd7e30fbc6a3099da0/mps_youtube/mpris.py#L462

**Comment by FichteFoll** [comment]
Ah right, I forgot that this is fundamentally how you access properties. For obious reasons, QDBusViewer uses introspection to show a bus's path's interfaces and the methods and properties they define, so it's understandable why I my method to "check" for them fell into the same trap as the library I use to access the properties in my tool (dbussy).

Judging from your reply I take that this is more of a problem of `dbus-python`?
