### ISSUE TITLE
[Feature Request] Allow access to current song url or id

### ISSUE THREAD

**Issue by nealot** [mps-youtube/mps-youtube#881]
Is it possible to fetch the current song url/id? If so, implementing https://github.com/mps-youtube/mps-youtube/issues/453 would become trivial.

Perhaps it could be added to the mpris metadata? I'm asking because I want to download the current song through a script.

**Comment by hrnr** [comment]
Currently MPRIS somewhat exports youtube id under metadata as "mpris:trackid". However because of dbus requirements '-_' characters are stripped from youtube ids.

See https://github.com/mps-youtube/mps-youtube/blob/eb9e5004728368a03dfd5a92ae94fb53895360e8/mps_youtube/mpris.py#L296-L305
https://www.youtube.com/watch?v=Rbt2NFCtBh4
I think we can easily export full ytids under 'xesam:url' field in metadata if you want. https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/#index20h4

URL would be fixed to 'https://www.youtube.com/watch?v=ytid', so you could easily parse just the ytid if needed. Would that work for your needs?

**Comment by nealot** [comment]
Ah, I guess I should have explored the track id before posting -- thanks for the solution! I'll consider this issue solved.

**Comment by hrnr** [comment]
Does #882 work for you?

**Comment by nealot** [comment]
Yeah it works, thanks!
