### ISSUE TITLE
Create playlist from list of urls

### ISSUE THREAD

**Issue by bburky** [mps-youtube/mps-youtube#90]
Is it currently possible to create a playlist from a list of urls?

Manually it would be possible with:

```
url https://www.youtube.com/watch?v=...
add 1
url https://www.youtube.com/watch?v=...
add 1
...
```

But this is tedious. My suggestion is to allow the `url` command to accept multiple urls.

I would like to pass in a list of urls from the command line, which this would make possible. I could run
`mpsyt url https://www.youtube.com/watch?v=... https://www.youtube.com/watch?v=... https://www.youtube.com/watch?v=...` or
`mpsyt url $(generate list of urls somehow)`.

Alternately you could read a list of urls from a file. Or allow multiple commands to be run from the command line.

**Comment by BensonQiu** [comment]
Hi,

[I'm](https://github.com/BensonQiu) working on a group project with [Femi](https://github.com/aquafemi), [Paul](https://github.com/paulnicolet), [Rohan](https://github.com/rjvani), and [Tommy](https://github.com/tommyhtc), and we're interested in contributing to mps-youtube. We don't have much experience with open source contributions, but we would like to work on [#90](https://github.com/mps-youtube/mps-youtube/issues/90), [#375](https://github.com/mps-youtube/mps-youtube/issues/375), and [#355](https://github.com/mps-youtube/mps-youtube/issues/355) as a group over the next 2-3 weeks. Would these contributions be helpful for the project?

We have read the [contributing](https://github.com/mps-youtube/mps-youtube/blob/develop/CONTRIBUTING) document, but we wanted to post here to express interest. We also wanted to see if anyone was already working on these issues. Since we would like to work on three open issues, I'm posting this message three times (sorry for the spam!).

Regards,
Benson, Femi, Paul, Rohan, and Tommy

**Comment by ids1024** [comment]
@BensonQiu Contributions are of course welcome. It probably would have been best to only post the message once though, since github shows a link when an issue is referenced in another issue, making the duplication a little redundant. But anyway...

This issue is not being worked on, though some thought has gone into #361 (as you can see there) which is somewhat related. Nor is there presently any work done on #374 and #355. So if you would like to implement these, go ahead.
